"""add location to bakery

Revision ID: 2f7b102c2e85
Revises: 1a660c242acb
Create Date: 2025-05-30 17:08:39.839997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b102c2e85'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakeries', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'location')
    # ### end Alembic commands ###
